### ISSUE TITLE
[PE-D] Print: no output other information only pin print

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W10-2/tp#203]
when only pin "print", it only shows student name without others
![Screenshot 2021-10-29 at 4.45.36 PM.png](https://raw.githubusercontent.com/zzybluebell/ped/main/files/74a60932-73d2-47c2-8ae7-198c3d039f1f.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: zzybluebell/ped#5

**Comment by yulonglim** [comment]
Not even an issue however might list out the columns generated for the success message
