### ISSUE TITLE
[PE-D] Bug for Docs. Comment not hidden

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W10-2/tp#208]
![image.png](https://raw.githubusercontent.com/EltonGohJH/ped/main/files/604d8ef3-20d2-4272-9867-8b4b5c5cab99.png)

This is suppose to a comment in markdown and not shown. There should be a GUI shown according to header too.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: EltonGohJH/ped#2

**Comment by fans2619** [comment]
Already fixed by Wilfred.
