### ISSUE TITLE
[PE-D] DeleteClass Command Feature Flaw

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W10-2/tp#213]
![image.png](https://raw.githubusercontent.com/EltonGohJH/ped/main/files/9a7cc494-81e7-42a4-a18f-5b24ddcd4a38.png)

I cant highlight the name of class to copy and paste. I think deleting by class name really slows the process a lot. Index will be a much better option.
The fact that it is different for student kept confusing me too.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: EltonGohJH/ped#4

**Comment by Wilfredwongkc** [comment]
Put a call-out and explain in the future we working on the using INDEX
