### ISSUE TITLE
[PE-D] List Absentee not working.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W10-2/tp#217]
![image.png](https://raw.githubusercontent.com/EltonGohJH/ped/main/files/d3280d14-f17b-4e0f-b671-3c0cc07a8696.png)

list absentee in the docs. But does not work.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: EltonGohJH/ped#8

**Comment by fans2619** [comment]
Fixed already.
